#!/usr/bin/env bash

# Generate AUTHORS file based on Git contributors

echo "# File generated by generate-authors.sh." > AUTHORS
echo "" >> AUTHORS

git log --format='%aN <%aE>' | sort -u >> AUTHORS

echo "" >> AUTHORS
echo "Thank you to everyone who has helped improve this project!" >> AUTHORS
